export const CV_DATA = {
  profile: {
    fullName: "Bastien Xerri",
    title: "",
    catchphrase: "Passionné par le digital, je mets mes compétences en webmarketing et gestion de projet au service du développement des marques.",
    about: "Titulaire d'un Master en Management du Sport, je poursuis actuellement un MBA en Stratégie Digitale. Fort de premières expériences en webmarketing, gestion de projet, SEO, CRM et création de contenus, je souhaite mettre mes compétences au service d'une marque forte et de son développement digital.",
    email: "bastienx2606@gmail.com",
    phone: "06 99 72 20 74",
    linkedin: "https://linkedin.com/in/bastien-xerri",
    location: "92160 - Antony",
    profilePic: "/profile.jpg",
  },
  experiences: [
    {
      role: "Assistant Webmarketing",
      company: "Centre International d'Antibes — Alternance",
      period: "Août 2025 - Présent",
      description: "Gestion et mise à jour du site web via intégration de contenus HTML. Gestion et envoi de campagnes emailing via Brevo CRM. Gestion et coordination des réseaux sociaux. Développement de l'engagement client. Suivi de projet, respect des délais et des objectifs web.",
      skills: ["HTML", "Brevo CRM", "SEO", "Réseaux sociaux"],
    },
    {
      role: "Gestionnaire Opérationnel Web & Locations",
      company: "CP Locations — Indépendant / Freelance",
      period: "Juin 2025 - Présent",
      description: "Dans le cadre d'une activité indépendante, je participe à la gestion opérationnelle du site CP Locations, dédié à la location de logements en Martinique. Suivi des réservations des logements. Consultation et mise à jour du calendrier des réservations. Suivi des disponibilités et organisation des plannings de nettoyage. Suivi des maintenances, réparations et remplacements. Gestion des paiements via Stripe et de la facturation. Mise à jour des informations sur le site et centralisation opérationnelle.",
      skills: ["Suivi Réservations", "Gestion de Calendrier", "Logistique"],
      link: "https://christinepetitlocations.vercel.app/"
    },
    {
      role: "Assistant Chef de Projet Web",
      company: "Mouratoglou Academy — Stage",
      period: "Janv. 2025 - Juil. 2025",
      description: "Gestion de projet : déploiement d'un SVI (Serveur Vocal Interactif) pour call center. Optimisation SEO et amélioration du classement sur Google. Intégration de contenus WordPress. Création de fiches informatives en HTML.",
      skills: ["WordPress", "SEO", "HTML", "Gestion de projet"],
    },
    {
      role: "Président",
      company: "KAZUR VIBES EVENTS — Association événementielle",
      period: "Fév. 2024",
      description: "Création de l'association et gestion administrative. Rédaction des statuts et organisation interne. Encadrement et management d'une équipe. Organisation et animation d'événements, accueil du public. Gestion budgétaire et suivi financier.",
      skills: ["Management", "Organisation", "Gestion budgétaire"],
    },
    {
      role: "Assistant Marketing",
      company: "Team Players — Stage",
      period: "Janv. 2024 - Juil. 2024",
      description: "Pilotage d'un projet d'optimisation des avis clients Google pour les centres LEFIVE et PADEL. Création de contenus pour les réseaux sociaux. Veille concurrentielle. Support marketing auprès des centres LEFIVE et 4PADEL.",
      skills: ["Marketing digital", "Réseaux sociaux", "Veille concurrentielle"],
    },
  ],
  education: [
    {
      degree: "MBA Stratégie Digitale",
      school: "Studi",
      period: "2025 - 2027",
      status: "En cours",
      info: "Spécialisation en stratégie digitale, webmarketing et e-commerce.",
    },
    {
      degree: "Master Management du Sport",
      school: "IAE / STAPS Nice",
      period: "2025",
      status: "Diplôme obtenu",
      info: "Développement Territorial par le Sport — Gestion d'équipes, développement de projets, dynamisation de territoire.",
    },
    {
      degree: "Licence Pro Santé & Activités Physiques Adaptées",
      school: "Université de Nice",
      period: "2023",
      status: "Diplôme obtenu",
      info: "Spécialisation Santé, Vieillissement et Activités Physiques Adaptées.",
    },
    {
      degree: "Licence Management du Sport",
      school: "IAE / STAPS Nice",
      period: "2022",
      status: "Diplôme obtenu",
      info: "Gestion, marketing et événementiel sportif.",
    },
  ],
  skillGroups: [
    {
      name: "Webmarketing & Digital",
      skills: ["SEO", "Email Marketing", "Automation", "CRM Brevo", "Réseaux sociaux", "Création de contenus", "Analyse KPIs", "Suivi de performance"],
    },
    {
      name: "Outils",
      skills: ["WordPress", "HTML", "Brevo", "Microsoft 365", "Excel", "Teams"],
    },
    {
      name: "Gestion de projet",
      skills: ["Suivi de projet", "Respect des délais", "Coordination", "Organisation", "Gestion budgétaire"],
    },
    {
      name: "Soft Skills",
      skills: ["Organisation", "Esprit d'équipe", "Autonomie", "Rigueur", "Communication", "Sens du contact", "Management"],
    },
  ],
  languages: [
    { name: "Français", level: "Langue maternelle" },
    { name: "Anglais", level: "B2" },
  ],
  permits: ["Permis B", "A1 (125)", "Permis côtier"],
  interests: ["Football", "Padel", "Tennis"],
  projects: [
    {
      title: "Campagnes Emailing CRM",
      description: "Gestion et envoi de campagnes emailing via Brevo CRM au Centre International d'Antibes — suivi des KPIs et optimisation du taux d'ouverture.",
      tags: ["Brevo CRM", "Email Marketing", "KPIs"],
      image: "",
      link: "#",
    },
    {
      title: "Déploiement SVI Mouratoglou",
      description: "Pilotage du projet de déploiement d'un Serveur Vocal Interactif pour le call center de la Mouratoglou Academy — coordination des équipes et suivi des délais.",
      tags: ["Gestion de projet", "SVI", "WordPress"],
      image: "",
      link: "#",
    },
    {
      title: "Optimisation SEO & Classement Google",
      description: "Amélioration du référencement naturel et du positionnement Google pour la Mouratoglou Academy — intégration de contenus optimisés.",
      tags: ["SEO", "WordPress", "HTML"],
      image: "",
      link: "#",
    },
    {
      title: "Avis Clients LEFIVE & 4PADEL",
      description: "Pilotage d'un projet d'optimisation des avis clients Google pour les centres sportifs LEFIVE et 4PADEL — création de contenus et veille concurrentielle.",
      tags: ["Marketing digital", "Réseaux sociaux"],
      image: "",
      link: "#",
    },
  ],
};
